version: '3.8'
services:
  app:
    container_name: liven-teste-back
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      - NODE_ENV=development
      - 'DB_HOST=postgres'
      - 'DB_PORT=5432'
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    networks:
      - liven-teste-network
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    container_name: liven-teste-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    networks:
      - liven-teste-network
    volumes:
      - liven-teste-postgres-volume:/data
    restart: unless-stopped

networks:
  liven-teste-network:
    name: liven-teste-network

volumes:
  liven-teste-postgres-volume:
    name: liven-teste-postgres-volume
