version: '3.8'
services:
  app:
    container_name: liven-teste-back
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    networks:
      - liven-teste-network
    restart: unless-stopped

networks:
  liven-teste-network:
    name: liven-teste-network

