FROM node:14
RUN mkdir -p /app/node_modules && chown -R node:node /app
WORKDIR /app
COPY package.json ./
USER node
RUN npm install
COPY --chown=node:node . .
RUN npm run build
EXPOSE 3333
CMD ["npm","run","dev"]
